language: php

php:
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phantomjs --ssl-protocol=any --ignore-ssl-errors=true src/Portergeist/Client/main.js 8510 1024 768 2>&1 >> /dev/null &
  - composer self-update
  - composer install --no-interaction

script:
  - bin/phpunit --configuration unit_tests.xml
  - bin/phpunit --configuration integration_tests.xml

after_script:
  - ps axo pid,command | grep phantomjs | grep -v grep | awk '{print $1}' | xargs -I {} kill {}
